---
title: "Homework 4 flexdashboard"
author: Yimiao Pang
data: November 6, 2021
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

## Problem 2

```{r 1.1, message=FALSE, collapse=TRUE}
# load data

data("instacart")

instacart1 = 
  instacart %>% 
  filter(department %in% c("produce", "dairy eggs", "snacks"))


```

# The order hour of the day for aisles in 3 most popular departments, produce, dairy eggs and snacks:

```{r}
instacart1 %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(x = ~aisle, y = ~order_hour_of_day, type = "box", color = ~aisle, colors = "viridis")
```

# The number of orders of aisles whose numbers are over 10000

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, colors = "viridis")
```

# Total number of orders in each day of a week

```{r}
instacart %>% 
  mutate(order_dow = factor(order_dow)) %>% 
  count(order_dow) %>% 
  mutate(order_dow = recode(order_dow, '0' = "Sunday", '1' = "Monday", '2' = "Tuesday", '3' = "Wednesday", '4' = "Thursday", '5' = "Friday", '6' = "Saturday")) %>% 
    mutate(text_label = str_c(order_dow, "\n# of orders: ", n)) %>% 
  plot_ly(x = ~order_dow, y = ~n, text = ~text_label, type = "scatter", mode = "lines+markers")
```

